import { describe, expect, it } from 'vitest';
import {
  generateHeader,
  generateSummaryPurpose,
  generateSummaryFileFormat,
  generateSummaryUsageGuidelines,
  generateSummaryNotes,
  generateSummaryAdditionalInfo,
} from '../../../src/core/output/outputStyleDecorate.js';
import type { repofmConfigMerged } from '../../../src/config/configSchema.js';

function makeConfig(overrides: Partial<repofmConfigMerged['output']> = {}): repofmConfigMerged {
  return {
    cwd: '/project',
    output: {
      filePath: 'output.txt',
      style: 'plain',
      removeComments: false,
      removeEmptyLines: false,
      topFilesLength: 5,
      showLineNumbers: false,
      copyToClipboard: false,
      ...overrides,
    },
    include: [],
    ignore: {
      useGitignore: true,
      useDefaultPatterns: true,
      customPatterns: [],
    },
    security: {
      enableSecurityCheck: true,
    },
  };
}

describe('outputStyleDecorate', () => {
  describe('generateHeader', () => {
    it('should include the generation date', () => {
      const date = '2024-01-15T12:00:00.000Z';
      const result = generateHeader(date);
      expect(result).toContain(date);
    });

    it('should include description about merged representation', () => {
      const result = generateHeader('2024-01-15');
      expect(result).toContain('merged representation');
    });

    it('should include "Generated by repofm on:"', () => {
      const result = generateHeader('2024-01-15');
      expect(result).toContain('Generated by repofm on:');
    });

    it('should not have leading or trailing whitespace (trimmed)', () => {
      const result = generateHeader('2024-01-15');
      expect(result).toBe(result.trim());
    });

    it('should return a non-empty string', () => {
      const result = generateHeader('2024-01-15');
      expect(result.length).toBeGreaterThan(0);
    });
  });

  describe('generateSummaryPurpose', () => {
    it('should mention packed representation', () => {
      const result = generateSummaryPurpose();
      expect(result).toContain('packed representation');
    });

    it('should mention AI systems', () => {
      const result = generateSummaryPurpose();
      expect(result).toContain('AI systems');
    });

    it('should return a non-empty string', () => {
      const result = generateSummaryPurpose();
      expect(result.length).toBeGreaterThan(0);
    });

    it('should be trimmed', () => {
      const result = generateSummaryPurpose();
      expect(result).toBe(result.trim());
    });
  });

  describe('generateSummaryFileFormat', () => {
    it('should mention the summary section', () => {
      const result = generateSummaryFileFormat();
      expect(result).toContain('summary');
    });

    it('should mention repository information', () => {
      const result = generateSummaryFileFormat();
      expect(result).toContain('Repository information');
    });

    it('should mention repository structure', () => {
      const result = generateSummaryFileFormat();
      expect(result).toContain('Repository structure');
    });

    it('should be trimmed', () => {
      const result = generateSummaryFileFormat();
      expect(result).toBe(result.trim());
    });
  });

  describe('generateSummaryUsageGuidelines', () => {
    it('should include read-only note', () => {
      const config = makeConfig();
      const result = generateSummaryUsageGuidelines(config, '');
      expect(result).toContain('read-only');
    });

    it('should include security note about sensitive information', () => {
      const config = makeConfig();
      const result = generateSummaryUsageGuidelines(config, '');
      expect(result).toContain('sensitive information');
    });

    it('should mention headerText context when headerText is provided', () => {
      const config = makeConfig({ headerText: 'My Project Description' });
      const result = generateSummaryUsageGuidelines(config, '');
      expect(result).toContain('Repository Description');
    });

    it('should not mention Repository Description when headerText is absent', () => {
      const config = makeConfig({ headerText: undefined });
      const result = generateSummaryUsageGuidelines(config, '');
      expect(result).not.toContain('Repository Description');
    });

    it('should mention Repository Instruction when repositoryInstruction is provided', () => {
      const config = makeConfig();
      const result = generateSummaryUsageGuidelines(config, 'Use TypeScript.');
      expect(result).toContain('Repository Instruction');
    });

    it('should not mention Repository Instruction when repositoryInstruction is empty', () => {
      const config = makeConfig();
      const result = generateSummaryUsageGuidelines(config, '');
      expect(result).not.toContain('Repository Instruction');
    });

    it('should be trimmed', () => {
      const config = makeConfig();
      const result = generateSummaryUsageGuidelines(config, '');
      expect(result).toBe(result.trim());
    });
  });

  describe('generateSummaryNotes', () => {
    it('should mention .gitignore rules', () => {
      const config = makeConfig();
      const result = generateSummaryNotes(config);
      expect(result).toContain('.gitignore');
    });

    it('should mention binary files', () => {
      const config = makeConfig();
      const result = generateSummaryNotes(config);
      expect(result).toContain('Binary files');
    });

    it('should include comment removal note when removeComments is true', () => {
      const config = makeConfig({ removeComments: true });
      const result = generateSummaryNotes(config);
      expect(result).toContain('Code comments have been removed');
    });

    it('should not include comment removal note when removeComments is false', () => {
      const config = makeConfig({ removeComments: false });
      const result = generateSummaryNotes(config);
      expect(result).not.toContain('Code comments have been removed');
    });

    it('should include line numbers note when showLineNumbers is true', () => {
      const config = makeConfig({ showLineNumbers: true });
      const result = generateSummaryNotes(config);
      expect(result).toContain('Line numbers have been added');
    });

    it('should not include line numbers note when showLineNumbers is false', () => {
      const config = makeConfig({ showLineNumbers: false });
      const result = generateSummaryNotes(config);
      expect(result).not.toContain('Line numbers have been added');
    });

    it('should be trimmed', () => {
      const config = makeConfig();
      const result = generateSummaryNotes(config);
      expect(result).toBe(result.trim());
    });
  });

  describe('generateSummaryAdditionalInfo', () => {
    it('should include GitHub link', () => {
      const result = generateSummaryAdditionalInfo();
      expect(result).toContain('https://github.com/chenxingqiang/repofm');
    });

    it('should return a non-empty string', () => {
      const result = generateSummaryAdditionalInfo();
      expect(result.length).toBeGreaterThan(0);
    });

    it('should be trimmed', () => {
      const result = generateSummaryAdditionalInfo();
      expect(result).toBe(result.trim());
    });

    it('should mention repofm', () => {
      const result = generateSummaryAdditionalInfo();
      expect(result).toContain('repofm');
    });
  });
});
